export const appSync = {
  queries: {
    getUser: () =>
      `query ($email:String!){
          getUser(email:$email) {
            id
            first_name
            last_name
          }
        }`,
    ListArchievedConversations: () =>
      `query ($token:String!,$user_id:String!){
          listArchivedConversations(
            token:$token,
            user_id:$user_id
          ){
            items{
            id
            type
            name
            profile_url
            members{
              id
              first_name
              last_name
            }
            messages{
              id
              content
              created_date
              is_pinned
              is_deleted
              is_starred
              media{
                id
                presigned_url
                file_path
                thumbnail_path
                type
                thumbnail_presigned_url
                created_date
                deleted_date
                updated_date
                is_deleted
              }
            }
            is_pinned
            unread
          }
        }
      }`,
    retrieveConversation: () =>
      `query ($token:String!,$user_id:String!,$conversation_id:String!,$type:String!){
        retrieveConversation( 
          token:$token,
          user_id:$user_id,
          conversation_id:$conversation_id,
          type:$type,
        ){
          id
          name
          profile_url
          type
          user{
            id
            first_name
            last_name
            email
            created_date
          }
          members{
            id
            email
            first_name
            last_name
            profile_url
            is_deleted
          }
          is_pinned
          total_member
          unread
        },  
        listMessages(
          user_id:$user_id,
          token:$token,
          conversation_id:$conversation_id
        ){
          items{
            id
            content
            created_date
            status
            is_pinned
            type
            is_deleted
            is_starred
            user{
              id
              first_name
              last_name
              profile_url
              created_date
            }
            media{
              id
              presigned_url
              file_path
              thumbnail_path
              type
              thumbnail_presigned_url
              created_date
              deleted_date
              updated_date
              is_deleted
            }
            reply_message{
              id
              content
              conversation_id
              created_date
              type
              status
              media{
                id
                presigned_url
                file_path
                thumbnail_path
                type
                thumbnail_presigned_url
                created_date
                deleted_date
                updated_date
                is_deleted
              }
              is_pinned
              is_deleted
              is_starred
              user{
                id
                first_name
                profile_url
                last_name
                email
                created_date
              }
              is_pinned
              is_deleted
              is_starred
            }
          }
    			next_token{
            id
            created_date
          }
        }
      }`,
    ListPinMessages:()=>
      `query ($token:String!,$conversation_id:String!,$search_text:String,$next_token:NextToken,$user_id:String!){
        listPinnedMessages(
          token: $token,
          conversation_id: $conversation_id,
          next_token: $next_token
          user_id: $user_id
          search_text: $search_text
        ){
          next_token{
            id
            created_date
          },
          items{
            id
            content
            conversation_id
            created_date
            type
            status
            media{
              id
              presigned_url
              file_path
              thumbnail_path
              type
              thumbnail_presigned_url
              created_date
              deleted_date
              updated_date
              is_deleted
            }
            reply_message{
              id
              content
              conversation_id
              created_date
              type
              status
              media{
                id
                presigned_url
                file_path
                thumbnail_path
                type
                thumbnail_presigned_url
                created_date
                deleted_date
                updated_date
                is_deleted
              }
              is_pinned
              is_deleted
              is_starred
              user{
                id
                first_name
                profile_url
                last_name
                email
              }
              is_pinned
              is_deleted
              is_starred
            }
            user{
              id
              first_name
              profile_url
              last_name
              email
            }
            is_pinned
            is_deleted
            is_starred
          }
        }
        }`
    ,
    ListStarMessages: () =>
      `query ($token:String!,$user_id:String!,$search_text:String,$next_token:NextToken){
      listStarredMessages(
        token:$token,
        user_id:$user_id,
        next_token:$next_token,
        search_text:$search_text
      ){
        next_token{
          id
          created_date
        },
        items{
            id
            content
            conversation_id
            created_date
            type
            status
            media{
              id
              presigned_url
              file_path
              thumbnail_path
              type
              thumbnail_presigned_url
              created_date
              deleted_date
              updated_date
              is_deleted
            }
            reply_message{
              id
              content
              conversation_id
              created_date
              type
              status
              media{
                id
                presigned_url
                file_path
                thumbnail_path
                type
                thumbnail_presigned_url
                created_date
                deleted_date
                updated_date
                is_deleted
              }
              is_pinned
              is_deleted
              is_starred
              user{
                id
                first_name
                profile_url
                last_name
                email
              }
              is_pinned
              is_deleted
              is_starred
            }
            user{
              id
              first_name
              profile_url
              last_name
              email
            }
            is_pinned
            is_deleted
            is_starred
          }
        }
      }
    `,
    // `query {
    //   retrieveConversation(
    //     token:"210109ef1ea70c711734fc3c7b9329b6",
    //     user_id:"d6f3fe32-2242-4353-aa03-7c941a8ad8cc",
    //     conversation_id:"17b9b836-36d9-479c-aa1d-385d58c6237f",
    //     type:"user",
    //     member_ids:["3ae8060b-5333-4bcc-b42b-d623368bf590"]
    //   ){
    //     id
    //     name
    //     profile_url
    //   },
    //   listMessages(
    //     user_id:"d6f3fe32-2242-4353-aa03-7c941a8ad8cc",
    //     token:"210109ef1ea70c711734fc3c7b9329b6",
    //     conversation_id:"17b9b836-36d9-479c-aa1d-385d58c6237f"
    //   ){
    //     items{
    //       id
    //       content
    //       user{
    //         id
    //         first_name
    //         last_name
    //       }
    //     }
    //   }
    // }`,
    ListMessges: () =>
      `query (
        $user_id:String!,
        $token:String!,
        $conversation_id:String!,
        $next_token:NextToken
      ){
          listMessages(
            user_id:$user_id,
            token:$token,
            conversation_id:$conversation_id,
            next_token:$next_token
          ){
            items{
              id
              content
              created_date
              status
              type
              is_pinned
              conversation_id
              is_deleted
              is_starred
              user{
                id
                first_name
                last_name
              }
              media{
                id
                presigned_url
                file_path
                thumbnail_path
                type
                thumbnail_presigned_url
                created_date
                deleted_date
                updated_date
                is_deleted
              }
              reply_message{
                id
                content
                conversation_id
                created_date
                type
                status
                media{
                  id
                  presigned_url
                  file_path
                  thumbnail_path
                  type
                  thumbnail_presigned_url
                  created_date
                  deleted_date
                  updated_date
                  is_deleted
                }
                is_pinned
                is_deleted
                is_starred
                user{
                  id
                  first_name
                  profile_url
                  last_name
                  email
                }
                is_pinned
                is_deleted
                is_starred
              }
          }
    			next_token{
            id
            created_date
          }
        }
    }`,
    ListConversation: () =>
      `query ($token:String!,$userId:String!,$search_text:String){
      listConversations(
        token:$token,
        user_id:$userId,
        search_text:$search_text
      ){
        items{
          id
          name
          profile_url
          is_pinned
          type
          total_member
          members{
            id
            first_name
            last_name
            profile_url
            is_deleted
          }
          messages{
            id
            content
            created_date
            status
            is_pinned
            conversation_id
            is_deleted
            is_starred
            user{
              id
              first_name
              last_name
            }
            media{
              id
              presigned_url
              file_path
              thumbnail_path
              type
              thumbnail_presigned_url
              created_date
              deleted_date
              updated_date
              is_deleted
            }
            reply_message{
              id
              content
              conversation_id
              created_date
              type
              status
              media{
                id
                presigned_url
                file_path
                thumbnail_path
                type
                thumbnail_presigned_url
                created_date
                deleted_date
                updated_date
                is_deleted
              }
              is_pinned
              is_deleted
              is_starred
              user{
                id
                first_name
                profile_url
                last_name
                email
              }
              is_pinned
              is_deleted
              is_starred
            }
          } 
          is_pinned
          unread
        }
      }
    }`,
  },
  mutations: {
    createConversation:()=>
    `mutation ($token:String!,$name:String,$profile_url:String,$user_id:String!,$type:String!,$member_ids:[String!]){
      createConversation(
        token:$token,
        user_id:$user_id,
        name:$name,
        profile_url:$profile_url,
        type:$type,
        member_ids:$member_ids
        ){
          id
          name
          created_date,
          type
          messages{
            id,
            content
          },
          user{
            id
            first_name
            last_name
          }
        }
    }`,
    updateMessageStatus:()=>
    `mutation ($token:String!,$message_id:String!,$conversation_id:String,$user_id:String!,$status:String!){
      updateMessageStatus(
        token:$token,
        conversation_id:$conversation_id,
        message_id:$message_id,
        user_id:$user_id,
        status:$status
      ){
        conversation_id
        user_id
        message_id
        status
      }
    }`,
    removeMember: () =>
      `mutation ($token:String!,$conversation_id:String!,$member_id:String!,$user_id:String!){
      removeMember(
        token:$token,
        conversation_id:$conversation_id,
        member_id:$member_id,
        user_id:$user_id
      ){
        conversation{
          id,
          name,
          members{
            id,
            first_name,
            last_name
            is_blocked
            is_deleted
          }
        }
        member_id
        conversation_id
      }
    }`,
    updateUserStatus: () =>
      `mutation ($token:String!,$conversation_id:String!,$user_id:String!,$status:String!){
        updateUserStatus(
          token:$token,
          conversation_id:$conversation_id,
          user_id:$user_id,
          status:$status
        ){
          conversation_id
          user_id
          status
        }
    }`,
    removeMember: () =>
      `mutation ($token:String!,$conversation_id:String!,$member_id:String!,$user_id:String!){
        removeMember(
          token:$token,
          conversation_id:$conversation_id,
          member_id:$member_id,
          user_id:$user_id
        ){
          conversation{
            id
            name
            profile_url
            type
            members{
              id
              first_name
              last_name
              profile_url
              is_deleted
            }
            is_pinned
            total_member
            unread
          },
          member_id,
          conversation_id
        }
      }`,
    editMessage: () =>
      `mutation ($token:String!,$message_id:String!,$user_id:String!,$content:String!,$type:String!){
      editMessage(
        token:$token,
        message_id:$message_id,
        user_id:$user_id,
        content:$content,
        type:$type
      ){
          id
          content
          type
          conversation_id
          created_date
          status
          is_pinned
          is_deleted
          is_starred
          user{
            id
            first_name
            last_name
          }
          media{
            id
            presigned_url
            file_path
            thumbnail_path
            type
            thumbnail_presigned_url
            created_date
            deleted_date
            updated_date
            is_deleted
          }
      }
    }`,
    deleteMessage: () =>
      `mutation ($token:String!,$user_id:String!,$message_id:String!,$delete_for:String!,$conversation_id:String){
      deleteMessage(
        token:$token,
        user_id:$user_id,
        message_id:$message_id,
        conversation_id:$conversation_id,
        delete_for:$delete_for
      ){
          is_deleted
          conversation_id
          message_id
          delete_for
      }
    }`,
    archiveConversation: () =>
      `mutation ($token:String!,$conversation_id:String!,$user_id:String!){
      archiveConversation(
        conversation_id:$conversation_id,
        token:$token,
        user_id:$user_id
      )
    }`,
    unarchiveConversation: () =>
      `mutation ($token:String!,$conversation_id:String!,$user_id:String!){
      unarchiveConversation(
        conversation_id:$conversation_id,
        token:$token,
        user_id:$user_id
      )
    }`,
    pinConversation: () =>
      `mutation ($token:String!,$conversation_id:String!,$user_id:String!,$action:Boolean!) {
        pinConversation(
          token: $token
          conversation_id: $conversation_id
          user_id: $user_id
          action:$action
        )
      }`,
    pinMessage: () =>
      `mutation ($token:String!,$message_id:String!,$action:Boolean!,$conversation_id:String!) {
      pinMessage(
        token: $token
        message_id: $message_id,
        conversation_id:$conversation_id,
        action: $action
      ){
        message_id
        action
        conversation_id
      }
    }`,
    starMessage: () =>
      `mutation ($token:String!,$message_id:String!,$user_id:String!,$action:Boolean!) {
       starMessage(token:$token,user_id:$user_id,message_id:$message_id,action:$action)
    }
    `,
    addUser: () =>
      `mutation addUser($first_name:String!,$last_name:String!,$email:String!){
        addUser(first_name:$first_name,last_name:$last_name,email:$email){
          first_name
        }
      }
      `,
    createToken: () =>
      `mutation {
            createToken{
              token
              encryption_enabled
            }
          }
      `,
    addMessage: () =>
      `mutation ($status:String,$token:String!,$type:String!,$reply_message_id:String,$message:String,$user_id:String!,$conversation_id:String,$media:[MediaInput]){
        addMessage(
          token:$token,
          type:$type,
          user_id:$user_id,
          conversation_id:$conversation_id,
          content:$message,
          reply_message_id:$reply_message_id
          media:$media
          status:$status
        ){
            id
            content
            created_date
            status
            is_pinned
            conversation_id
            is_deleted
            is_starred
            user{
              id
              first_name
              last_name
              email
              created_date
            }
            media{
              id
              presigned_url
              file_path
              thumbnail_path
              type
              thumbnail_presigned_url
              created_date
              deleted_date
              updated_date
              is_deleted
            }
            reply_message{
              id
              content
              conversation_id
              created_date
              type
              status
              media{
                id
                presigned_url
                file_path
                thumbnail_path
                type
                thumbnail_presigned_url
                created_date
                deleted_date
                updated_date
                is_deleted
              }
              is_pinned
              is_deleted
              is_starred
              user{
                id
                first_name
                profile_url
                last_name
                email
              }
              is_pinned
              is_deleted
              is_starred
            }
        }
      }`,
    addMediaMessage: () =>
      `mutation ($token:String!,$conversation_id:String!,$user_id:String!){
      addMessage(
        token:$token
        conversation_id:$conversation_id			
        user_id:$user_id
        type: "media"
        media:[
          {
            type:"image"
            file_path:"mediaAttachments/images/ad595e85-0752-4cab-bf8c-10413a1fea2e-1604473092113_WhatsApp Image 2020-10-17 at 12.06.07 PM.jpeg"
          }
        ]
      ){
        id
        is_pinned
        is_deleted
        is_starred
        content
        conversation_id
        type
        created_date
        media{
            id
            presigned_url
            file_path
            thumbnail_path
            type
            thumbnail_presigned_url
            created_date
            deleted_date
            updated_date
            is_deleted
          }
      }
    }`,
  },
  subscriptions: {
    subscribeToPinMessage: () =>
      `subscription ($conversation_id:String!){
        subscribeToPinMessage(conversation_id:$conversation_id){
          message_id
          action
          conversation_id      
        }
    }`,
    subscribeToEditMessage: () =>
      `subscription ($conversation_id:String!){
        subscribeToEditMessage(conversation_id:$conversation_id){
            id
            type
            content
            created_date
            status
            conversation_id
            is_pinned
            is_deleted
            is_starred
            user{
              id
              first_name
              last_name
            }
            media{
              id
              presigned_url
              file_path
              thumbnail_path
              type
              thumbnail_presigned_url
              created_date
              deleted_date
              updated_date
              is_deleted
            }
            reply_message{
              id
              content
              conversation_id
              created_date
              type
              status
              media{
                id
                presigned_url
                file_path
                thumbnail_path
                type
                thumbnail_presigned_url
                created_date
                deleted_date
                updated_date
                is_deleted
              }
              is_pinned
              is_deleted
              is_starred
              user{
                id
                first_name
                profile_url
                last_name
                email
              }
              is_pinned
              is_deleted
              is_starred
            }
        }
      }`,
    subscribeToRemoveMember: () =>
      `subscription ($conversation_id:String!){
        subscribeToRemoveMember(conversation_id:$conversation_id){
          conversation{
            id
            name
          }
          member_id
          conversation_id
        }
    }`,
    subscribeToUpdateUserStatus: () =>
      `subscription ($conversation_id: String!){
        subscribeToUpdateUserStatus(
          conversation_id:$conversation_id
          ){
          conversation_id
          user_id
          status
        }
      }
    `,
    subscribeToDeleteMessage: () =>
      `subscription ($conversation_id:String!){
        subscribeToDeleteMessage(
          conversation_id:$conversation_id,
        ){
          is_deleted
          conversation_id
          message_id
          delete_for
        }
      }`,
      subscribeToAddMessageConversation:()=>
      `subscription ($conversation_id:String!){
        subscribeToAddMessage(conversation_id:$conversation_id)
        {
            id
            content
            created_date
            status
            conversation_id
            is_pinned
            is_deleted
            is_starred
            user{
              id
              first_name
              last_name
              email
              created_date
            }
            media{
              id
              presigned_url
              file_path
              thumbnail_path
              type
              thumbnail_presigned_url
              created_date
              deleted_date
              updated_date
              is_deleted
            }
            reply_message{
              id
              content
              conversation_id
              created_date
              type
              status
              media{
                id
                presigned_url
                file_path
                thumbnail_path
                type
                thumbnail_presigned_url
                created_date
                deleted_date
                updated_date
                is_deleted
              }
              is_pinned
              is_deleted
              is_starred
              user{
                id
                first_name
                profile_url
                last_name
                email
              }
              is_pinned
              is_deleted
              is_starred
            }
        }
      }`,
    subscribeToAddMessage: () =>
      `subscription ($conversation_id:String!){
        subscribeToAddMessage(conversation_id:$conversation_id)
        {
            id
            content
            created_date
            status
            conversation_id
            is_pinned
            is_deleted
            is_starred
            user{
              id
              first_name
              last_name
              email
              created_date
            }
            media{
              id
              presigned_url
              file_path
              thumbnail_path
              type
              thumbnail_presigned_url
              created_date
              deleted_date
              updated_date
              is_deleted
            }
            reply_message{
              id
              content
              conversation_id
              created_date
              type
              status
              media{
                id
                presigned_url
                file_path
                thumbnail_path
                type
                thumbnail_presigned_url
                created_date
                deleted_date
                updated_date
                is_deleted
              }
              is_pinned
              is_deleted
              is_starred
              user{
                id
                first_name
                profile_url
                last_name
                created_date
                email
              }
              is_pinned
              is_deleted
              is_starred
            }
        }
      }`,
  },
};
